version: '3'
services:
  web:
    image: "node:11.0.0"
    restart: always
    user: "node"
    working_dir: /home/node/app
    volumes:
      - /home/node/app:/home/node/app
      - /etc/letsencrypt:/home/node/app/cert
    ports:
      - "80:5000"
      - "443:5443"
    command: "yarn server:start"
    links:
      - db
    env_file:
      - .env.production
    environment:
     - NODE_ENV=production

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env.production
    environment:
       - NODE_ENV=production
    volumes:
      - /root/data/:/data/db
